package api

const (
	BACKSLASH                  string = "\\"
	PAREN_OPEN                 string = "("
	PAREN_CLOSE                string = ")"
	LESS_THAN                  string = "<"
	GREATER_THAN               string = ">"
	OPEN_CURLY_BRACE           string = "{"
	CLOSE_CURLY_BRACE          string = "}"
	OPEN_SQUARE_BRACKET        string = "["
	CLOSE_SQUARE_BRACKET       string = "]"
	CARAT                      string = "^"
	DOLLAR                     string = "$"
	HYPHEN                     string = "-"
	PLUS                       string = "+"
	ASTERISK                   string = "*"
	QUESTION_MARK              string = "?"
	COLON                      string = ":"
	COMMA                      string = ","
	PERIOD                     string = "."
	WORD_BOUNDARY              string = BACKSLASH + "b"
	NON_WORD_BOUNDARY          string = BACKSLASH + "B"
	BEGINNING_OF_TEXT          string = BACKSLASH + "A"
	END_OF_TEXT                string = BACKSLASH + "z"
	QUOTE_START                string = BACKSLASH + "Q"
	QUOTE_END                  string = BACKSLASH + "E"
	ALTERNATION                string = "|"
	NAMED_CAPTURE_GROUP_PREFIX string = "P"
)
